name: En action på en release!
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello 
        uses: sjodin91/hello-world-docker-action@v3
        with:
          who-to-greet: '@octocat'