name: GitHub DEPLOY

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  
      - uses: actions/checkout@v3.3.0
  
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  Deploy:
    name: Deploy-${{ inputs.environment}}
    environment: 
      name: ${{ inputs.environment}}
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: echo "deploy this scrapt ....." 
      
   
